name: Run test_twi.py on Push or Pull Request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-script:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium google-api-python-client google-auth-httplib2 google-auth-oauthlib Pillow requests
      - name: Run script
        env:
          DATAMB_EMAIL: ${{ secrets.DATAMB_EMAIL }}
          DATAMB_PASSWORD: ${{ secrets.DATAMB_PASSWORD }}
          BUFFER_EMAIL: ${{ secrets.BUFFER_EMAIL }}
          BUFFER_PASSWORD: ${{ secrets.BUFFER_PASSWORD }}
          BUFFER_API_KEY: ${{ secrets.BUFFER_API_KEY }}
        run: |
          python test_twi.py
